default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: movement_central_development
  host: localhost
  username: vincentshieh

test:
  <<: *default
  database: movement_central_test
